# Generated by Django 4.1.3 on 2022-12-13 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Img_url', models.CharField(max_length=250)),
                ('discription', models.TextField()),
                ('owner', models.ManyToManyField(related_name='Auction_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
