# Generated by Django 4.1.3 on 2022-12-13 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bidder', models.ManyToManyField(related_name='Bid', to=settings.AUTH_USER_MODEL)),
                ('item', models.ManyToManyField(related_name='Bid', to='auctions.auction_item')),
            ],
        ),
    ]
