# Generated by Django 4.1.3 on 2022-12-13 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auction_item_owner_auction_item_atchlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_item',
            old_name='atchlist',
            new_name='watchlist',
        ),
        migrations.AddField(
            model_name='auction_item',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
