# Generated by Django 4.1.3 on 2022-12-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_item_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_item',
            old_name='discription',
            new_name='description',
        ),
    ]
