# Generated by Django 4.1.3 on 2022-12-13 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_discription_auction_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ManyToManyField(related_name='Bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='item',
            field=models.ManyToManyField(related_name='Bid_item', to='auctions.auction_item'),
        ),
    ]
