# Generated by Django 4.1.3 on 2022-12-14 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_input',
        ),
    ]
