# Generated by Django 4.1.3 on 2022-12-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_comment_comment_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
