# Generated by Django 4.1.3 on 2022-12-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auction_item_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
