# Generated by Django 4.1.3 on 2022-12-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_category_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='items',
        ),
    ]
