# Generated by Django 4.1.3 on 2022-12-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_remove_category_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_item',
            field=models.ManyToManyField(related_name='Cat_item', to='auctions.auction_item'),
        ),
    ]
